# Generated by Django 5.2.2 on 2025-06-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_created_on_task_description_task_due_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', '🔴 High'), ('2', '🟠 Medium'), ('3', '🟢 Low')], default='3'),
        ),
    ]
